---
- hosts: all
  remote_user: root
  vars:
    compose_directory: /data/monitoring.minetest.ch
  tasks:
    - name: Checkout git master
      ansible.builtin.git:
        repo: https://github.com/minetest-monitoring/monitoring.minetest.ch
        dest: "{{ compose_directory }}"
        force: yes
        version: master

    - name: Template docker-compose.yml
      template:
        src: "docker-compose.yml"
        dest: "{{compose_directory}}/docker-compose.yml"

    - name: Template prometheus.yml
      template:
        src: "config/prometheus.yml"
        dest: "{{compose_directory}}/config/prometheus.yml"

    - name: Create and start services
      community.general.docker_compose:
        project_src: "{{ compose_directory }}"
        pull: yes
        build: yes
        remove_orphans: yes
