global:
    scrape_interval: 5s
    external_labels:
     monitor: 'my-monitor'

scrape_configs:
    # pushgateway for the minetest-monitoring mod
    - job_name: 'minetest'
      honor_labels: true
      static_configs:
       - targets: ['pushgateway:9091']

    # public minetest-related nodes
    - job_name: 'nodes'
      static_configs:
      - targets:
        - phlegethon.rudin.io:9100
        - styx.rudin.io:9100

    # minetest git hosting
    - job_name: 'gitea'
      static_configs:
      - targets:
        - git.minetest.land

    # traefik metric for the minetest-nodes
    - job_name: 'traefik'
      basic_auth:
       username: admin
       password: {{traefik_password}}
      static_configs:
      - targets:
        - phlegethon.rudin.io
        - styx.rudin.io

    # mapserver metrics
    - job_name: 'mapserver'
      scheme: https
      metrics_path: /map/metrics
      static_configs:
       - targets: ['pandorabox.io']

    # emscripten-based minetest client
    - job_name: 'mtweb'
      scheme: https
      static_configs:
       - targets: ['web.minetest.ch']

    # blockexchange instance
    - job_name: 'blockexchange'
      scheme: https
      static_configs:
       - targets: ['blockexchange.minetest.ch']

    # minetest-engine exporter
    - job_name: 'minetest-engine'
      scheme: https
      metrics_path: /minetest-exporter/metrics
      static_configs:
       - targets: ['pandorabox.io', 'test.pandorabox.io', 'bananaland.minetest.ch']

    # blackbox exporter for various hosts
    - job_name: 'blackbox'
      scrape_interval: 1m
      params:
       module: [http_2xx]
      metrics_path: /probe
      static_configs:
      - targets:
        - https://pandorabox.io/
        - https://hosting.minetest.ch
        - https://blockexchange.minetest.ch
        - https://monitoring.luanti.ch
        - https://content.minetest.net
        - https://forum.minetest.net
        - https://wiki.minetest.net
        - https://www.minetest.net
        - https://servers.minetest.net
      relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
